spring:
  resource:
    server:
      config:
        resource_id: resource-server-rest-api
  datasource:
    url: jdbc:postgresql://192.168.123.252:5433/oauth2
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    initialization-mode: always
    hikari:
      connection-timeout: 40000
      minimum-idle: 50
      maximum-pool-size: 70
      idle-timeout: 20000
      max-lifetime: 2000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        id:
          new_generator_mappings: true
        jdbc:
          lob:
            non_contextual_creation: true
  mail:
    host: email-smtp.us-west-2.amazonaws.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
            required: false
  http:
    log-request-details: true

  queries:
    users-query: select user_name as email, password, enabled as active from user_ where user_name=?
    email-query: select email, password, enabled as active from user_ where email=?
    roles-query-user: select u.email as email, r.name as role from user_ u inner join user_role ur on(u.id=ur.user_id) inner join role_ r on(ur.role_id=r.id) where u.user_name=?
    roles-query-email: select u.email as email, r.name as role from user_ u inner join user_role ur on(u.id=ur.user_id) inner join role_ r on(ur.role_id=r.id) where u.email=?

logging:
  level:
    org:
      springframework:
        security: DEBUG
          oauth2: debug
        web: DEBUG
      hibernate: debug
        SQL: debug
        type:
          descriptor:
            sql: trace

hibernate:
  show_sql: true

jwt:
  secret: ${JWT_SECRET}
  token:
    validity: 18000

app:
  mail_confirmation_link: http://stage.lqwd.tech:30100


log4j:
  logger:
    org:
      hibernate:
        type: trace

