spring:
  kafka:
    bootstrap-servers: 192.168.123.252:9092
    enable:
      auto:
        commit: true
    auto:
      commit:
        interval:
          ms: 10000
    session:
      timeout:
        ms: 30000
    consumer:
      timeout:
        ms: 120000
    jaas:
      enabled: true
    properties:
      security:
        protocol: SASL_PLAINTEXT
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="" user_admin="" user_kafka="";
    admin:
      ssl:
        key-password: ${KEY_PASSWORD}
        key-store-location: file:src/main/resources/kafka.server.keystore.jks
        key-store-password: ${KEY_STORE_PASSWORD}
        trust-store-location: file:src/main/resources/kafka.server.truststore.jks
        trust-store-password: ${TRUST_STORE_PASSWORD}

  cloud:
    stream:
      default:
        producer:
          useNativeEncoding: true
        consumer:
          useNativeEncoding: true
      bindings:
        input:
          destination: tmessage-details
          content-type: application/*+avro
          group: group-1
        output:
          destination: tmessage-details
          content-type: application/*+avro
      kafka:
        binder:
          producer-properties:
            key:
              serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            value:
              serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema:
              registry:
                url: http://192.168.123.252:8081
          consumer-properties:
            key:
              deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            value:
              deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema:
              registry:
                url: http://192.168.123.252:8081
            specific:
              avro:
                reader: true
server:
  ssl:
    key-store: 'file:src/main/resources/keystore.jks'
    key-store-password: ${KEY_STORE_PASSWORD}


app:
  auth_post_url: 192.168.123.252
  auth_post_port: 8187
  auth_user_name: ${AUTH_USERNAME}
  auth_password: ${AUTH_PASSWORD}
  auth_grand_type: ${AUTH_GRANT_TYPE}

grpc:
  client:
    target: 192.168.123.252:8080
